python3 js_analyzer.py slices/1-basic-flow/1a-basic-flow.js slices/1-basic-flow/1a-basic-flow.patterns.json
python3 js_analyzer.py slices/1-basic-flow/1b-basic-flow.js slices/1-basic-flow/1b-basic-flow.patterns.json
python3 js_analyzer.py slices/2-expr-binary-ops/2-expr-binary-ops.js slices/2-expr-binary-ops/2-expr-binary-ops.patterns.json
python3 js_analyzer.py slices/3-expr/3a-expr-func-calls.js slices/3-expr/3a-expr-func-calls.patterns.json
python3 js_analyzer.py slices/3-expr/3b-expr-func-calls.js slices/3-expr/3b-expr-func-calls.patterns.json
python3 js_analyzer.py slices/3-expr/3c-expr-attributes.js slices/3-expr/3c-expr-attributes.patterns.json  
python3 js_analyzer.py slices/4-conds-branching/4a-conds-branching.js slices/4-conds-branching/4a-conds-branching.patterns.json
python3 js_analyzer.py slices/4-conds-branching/4b-conds-branching.js slices/4-conds-branching/4b-conds-branching.patterns.json
python3 js_analyzer.py slices/5-loops/5a-loops-unfolding.js slices/5-loops/5a-loops-unfolding.patterns.json
python3 js_analyzer.py slices/5-loops/5b-loops-unfolding.js slices/5-loops/5b-loops-unfolding.patterns.json
python3 js_analyzer.py slices/5-loops/5c-loops-unfolding.js slices/5-loops/5c-loops-unfolding.patterns.json
python3 js_analyzer.py slices/6-sanitization/6a-sanitization.js slices/6-sanitization/6a-sanitization.patterns.json
python3 js_analyzer.py slices/6-sanitization/6b-sanitization.js slices/6-sanitization/6b-sanitization.patterns.json
python3 js_analyzer.py slices/7-conds-implicit/7-conds-implicit.js slices/7-conds-implicit/7-conds-implicit.patterns.json
python3 js_analyzer.py slices/8-loops-implicit/8-loops-implicit.js slices/8-loops-implicit/8-loops-implicit.patterns.json
python3 js_analyzer.py slices/9-regions-guards/9-regions-guards.js slices/9-regions-guards/9-regions-guards.patterns.json